# Generated by Django 3.2.7 on 2021-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapipostdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='datetimeofupdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
